AWSTemplateFormatVersion: '2010-09-09'
Description: Creating Application Load Balancer 

Resources:

  # Creating Application Load Balancer with name 'tm-devops-trainee-alb'
  MyALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - !ImportValue PublicSubnet1
        - !ImportValue PublicSubnet2
      SecurityGroups:
        - !ImportValue MyALBSecurityGroup
      Tags:
        - Key: Name
          Value: 'tm-devops-trainee-alb'

  # Creating Application Load Balancer Listener
  MyALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: MyALB
    Properties:
      LoadBalancerArn: !Ref MyALB
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup

  # Creating Application Load Balancer Target Group
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: ALBTargetGroup
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: !ImportValue MyVPC
      TargetType: ip 


Outputs:
  # Export Application Load Balancer Target Group and Application Load Balancer DNS Name values
  ExternalUrl:
    Description: The url of the external load balancer
    Value: !Sub http://${MyALB.DNSName}

  ALBTargetGroup:
    Description: ALBTargetGroup
    Value: !Ref ALBTargetGroup
    Export:
      Name: 'ALBTargetGroup'