AWSTemplateFormatVersion: '2010-09-09'
Description: Create Security groups for ALB, Container and EFS

Resources:
  MyALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Security Group
      VpcId: !ImportValue MyVPC
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: '0.0.0.0/0'

  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to the containers
      VpcId: !ImportValue MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          SourceSecurityGroupId: !Ref MyALBSecurityGroup

  EFSFileSystemSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EFS file system
      VpcId: !ImportValue MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          SourceSecurityGroupId: !Ref ContainerSecurityGroup

Outputs:
  MyALBSecurityGroup:
    Description: MyALBSecurityGroup
    Value: !Ref MyALBSecurityGroup
    Export:
      Name: 'MyALBSecurityGroup'

  ContainerSecurityGroup:
    Description: ContainerSecurityGroup
    Value: !Ref ContainerSecurityGroup
    Export:
      Name: 'ContainerSecurityGroup'

  EFSFileSystemSecurityGroup:
    Description: EFSFileSystemSecurityGroup
    Value: !Ref EFSFileSystemSecurityGroup
    Export:
      Name: 'EFSFileSystemSecurityGroup'
#need delete
 # MyALBSecurityGroupId:
 #   Description: ALB Security Group ID
 #   Value: !GetAtt MyALBSecurityGroup.GroupId
 #   Export:
 #     Name: 'MyALBSecurityGroupId'